// Tom's information (need to update if I want to use my own amplify)
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsconfig = {
  aws_project_region: "eu-west-1",
  aws_cognito_identity_pool_id:
    "eu-west-1:0a68332f-1d01-4fe1-a908-44d1a12ed79c",
  aws_cognito_region: "eu-west-1",
  aws_user_pools_id: "eu-west-1_ldtrXGQxj",
  aws_user_pools_web_client_id: "30a6qvioihdhp5hnhqqikhjr0n",
  oauth: {},
  aws_cognito_login_mechanisms: ["EMAIL"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};
export default awsconfig;
